version: '3.8'
services:
  smugmug-sync:
    image: smugmug-sync-pro:latest
    container_name: smugmug_backup
    read_only: true  # <--- Locks the container filesystem
    tmpfs:
      - /tmp         # <--- Gives Python a place for temporary files
    env_file: .env
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - NICKNAME=${NICKNAME}
      - PYTHONDONTWRITEBYTECODE=1 # <--- Prevents writing .pyc files
    volumes:
      - /volume2/Photos/smugmug-backup:/data
    restart: unless-stopped
